config/routes.rb
Pinballopen::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/faq"
  get "static_pages/about"
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

  resources :tables

  resources :tournaments, only: [:new, :create, :edit, :update, :show] do
    member { get 'init' }
    resources :phases, only: [:create, :edit, :update, :show]
    resources :qualifications, only: [:create, :edit, :update, :show], controller: :phases, type: :qualification
    resources :matches
  end

  root 'static_pages#home'

  resources :roles

  resources :nationalities

  controller :users do
    get 'register' => :new
    get 'password' => :request_password_reset
    post 'password' => :process_password_reset
  end

  resources :users do
    get 'activate' => 'users#activate'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_secure_token
  has_and_belongs_to_many :phases
  has_and_belongs_to_many :tournaments

  before_validation :capitalize_names
  before_validation :downcase_email

  belongs_to :nationality
  has_and_belongs_to_many :roles
  has_many :scores
  has_many :matches, through: :scores

  validates :first_name, :last_name, :email, :password_digest, presence: true
  validates :nationality_id, inclusion: { in: Nationality.ids }
  validates :email, format: { with: /\A[a-zA-Z0-9\.\+_]+@[a-zA-Z0-9_]+\.[a-zA-Z]+/}
  validates :email, uniqueness: { case_sensitive: false }
  validate :check_uniqueness_of_full_name, on: :create

  def self.get_player_count
    player = Role.find_by_name('Player')
    self.all.map { |user| user.roles.index(player) }.compact.length
  end

  def get_player_full_name
    self.first_name + " " + self.last_name
  end

  private

    def check_uniqueness_of_full_name
      if not User.find_by(first_name: first_name, last_name: last_name).nil?
        errors.add :first_name, 'Player with this name already exists'
        errors.add :last_name, 'Player with this name already exists'
      end
    end

    def capitalize_names
      first_name.capitalize!
      last_name.capitalize!
    end

    def downcase_email
      email.downcase!
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :activate, :index, :edit, :update, :request_password_reset, :process_password_reset]
  before_action :authorize_this_user_only, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @matches_played_by_player = Match.joins(:scores).where("scores.user_id" => @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def request_password_reset
    @user = User.new
  end

  def process_password_reset
    @user = User.find_by_email(user_params[:email].downcase)
    if not @user
      flash[:type] = :danger
      flash[:message] = "Email not registered."
      redirect_to password_url
      return false
    end
    @user.regenerate_token
    UserNotifier.pass_reset(@user).deliver
    flash[:type] = :success
    flash[:message] = "Check your inbox for password reset instruction."
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new set_player_role # TODO this is bad!
    @user.tournaments << Tournament.first # TODO fix fixed tournmanet assignemt

    respond_to do |format|
      if @user.save
        UserNotifier.created(@user).deliver
        format.html { render action: 'create' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # get /users/:id/activate
  def activate
    if params[:token]
      @user = User.find_by_token(params[:token])
      if not @user.active? and @user.id == params[:user_id].to_i
        respond_to do |format|
          if @user.update active: true
            session[:user_id] = @user.id
            UserNotifier.activated(@user).deliver
            format.html { redirect_to @user, notice: 'Your account is activated now. Thanks' }
          else
            format.html { redirect_to root_url }
          end
        end
      end
    else
      redirect_to root_url
    end
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update user_params
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :nationality_id, :password, :password_confirmation, :email, :roles => [] )
    end

    def convert_roles_to_objects
      params = user_params
      params[:roles].map! do |role|
        if not role.empty?
          Role.find(role)
        end
      end.compact!
      params
    end

    def set_player_role
      params = user_params
      params[:roles] = [Role.find_by_name('Player')]
      params
    end

    def authorize_this_user_only
      user = User.find(params[:id])
      if user
        if params[:token] and user.token and params[:token] == user.token
          session[:user_id] = params[:id]
          user.token = nil
          user.save
          return true
        else
          return true if user.id == session[:user_id].to_i
        end
      end
      redirect_to login_url, notice: 'Permission denied'
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def form_with_error_handling(name, &html)
     error = !@user.errors[name].empty?
     content_tag(:div, class: "form-group #{'form-group-no-margin-bottom' if error}") do
        content_tag(:div, class: nil) do
          res = [] << content_tag(:div, class: "input-group has-feedback #{'has-error' if error }") do
            res = []
            res << content_tag(:span, class: 'input-group-addon new-user-group-addon') do
              if name == :password_confirmation
                n = :confirm
              elsif name == :nationality_id
                n = :nationality
              else
                n = name
              end
              n.to_s.split(/_/).map {|t| t.capitalize }.join(" ")
            end
            res.append(yield html)
            if error
              res << content_tag(:span, class: 'form-control-feedback glyphicon glyphicon-remove') {}
            end
            res.join.html_safe
          end
          if error
            res << content_tag(:strong, @user.errors[name].first, class: 'help-block', style: 'color: red;')
          end
          res.join.html_safe
        end
      end
  end
end

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <%= form_for(@user, html: { class: 'form-horizontal', role: 'form' } ) do |f| %>

        <%= form_with_error_handling(:email) { f.text_field(:email, class: 'form-control input-sm') } %>
        <%= form_with_error_handling(:first_name) { f.text_field :first_name, class: 'form-control input-sm'} %>
        <%= form_with_error_handling(:last_name) { f.text_field :last_name, class: 'form-control input-sm' } %>
        <%= form_with_error_handling(:nationality_id) { f.select :nationality_id,
                                                                  options_for_select(Nationality.all.map { |n| [n.name, n.id]}),
                                                                  {}, { class: 'form-control select-picker'} } %>
        <%= form_with_error_handling(:password) { f.password_field :password, class: 'form-control input-sm'} %>
        <%= form_with_error_handling(:password_confirmation) { f.password_field :password_confirmation, class: 'form-control input-sm' } %>
        <div class="actions text-center">
        <%= f.submit 'Register', class: 'btn btn-primary' %><br>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<div class="container">
  <div class="alert alert-success">
    <div class="text-center">
      Registration complete. We have sent you an email with activation link. Please click on it to activate your account.
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
<div class="col-lg-6">
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <td>Name</td>
        <td>Nationality</td>
        <td>Roles</td>
        <td>Activated?</td>
        <td>Actions</td>
      </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name + ' ' + user.last_name %></td>
            <td><%= image_tag user.nationality.flag_img_path, class: 'flag_class' %></td>
            <td class="roles">
              <ul>
                <% user.roles.each do |role| %>
                    <li><%= role.name %></li>
                <% end %>
              </ul>
            </td>
            <td class="activated">
              <%= user.active? %>
            </td>
            <td>
              <%= link_to 'Show', user, class: 'btn btn-info btn-xs' %>
              <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-warning btn-xs' %>
<!--
              <%= link_to 'Destroy', user, method: :delete,
                          data: { confirm: 'Are you sure?' },
                          class: 'btn btn-danger btn-xs' %>
-->
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>
  <%= link_to 'New User', new_user_path, class: 'btn btn-primary btn-large' %>
</div>
  <!--<div class="col-lg-6">test</div>-->
</div>

app/views/users/new.html.erb
<div class="container text-center">
  <h1>New Player</h1>
</div>
<%= render 'form' %>

app/views/users/process_password_reset.html.erb
<%= render 'shared/alert_box' %>

app/views/users/request_password_reset.html.erb
<%= render 'shared/alert_box' %>
<div class="container">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="form">
      <%= form_for @user, url: password_path do |f| %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.submit :reset %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if notice %>
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="alert alert-warning">
            <%= notice %>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2" style="background: lightgoldenrodyellow;">
      <h2 class="text-center">Profile Data</h2>
      <p><%= "Name: #{@user.get_player_full_name}" %></p>
      <p><%= "Nationality: #{@user.nationality.name}" %></p>
      <p>Something else</p>
      <%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-primary' %>
    </div>
    <div class="col-sm-10">
      <h2 class="text-center">Current phase: <%= Tournament.first.get_current_phase.name %></h2>
      <table class="table table-responsive">
        <thead style="background: greenyellow;">
          <tr>
            <td>Table</td>
            <td>Score</td>
            <td>Points</td>
            <td>Table's standing</td>
          </tr>
        </thead>
        <tbody>
          <% @matches_played_by_player.each do |match| %>
            <% table = Table.find(match.table_id) %>
            <tr>
              <td><%= table.name %></td>
              <td><%= @matches_played_by_player.joins(:scores).select("scores.value").where("matches.table_id" => table.id).first.value %></td>
              <td><%= table.get_points_for_player_in_current_phase(params[:id], Tournament.first.get_current_phase) %></td> <!-- TODO: fixed Tournament!! -->
              <td><%= table.get_player_standing_at_table_in_current_phase(params[:id], Tournament.first.get_current_phase) %></td> <!-- TODO: as above -->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>