config/routes.rb
Pinballopen::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/faq"
  get "static_pages/about"
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'

  resources :tables

  resources :tournaments, only: [:new, :create, :edit, :update, :show] do
    member { get 'init' }
    resources :phases, only: [:create, :edit, :update, :show]
    resources :qualifications, only: [:create, :edit, :update, :show], controller: :phases, type: :qualification
    resources :matches
  end

  root 'static_pages#home'

  resources :roles

  resources :nationalities

  controller :users do
    get 'register' => :new
    get 'password' => :request_password_reset
    post 'password' => :process_password_reset
  end

  resources :users do
    get 'activate' => 'users#activate'
  end

end

app/models/double_ko.rb
class DoubleKO < Phase
end

app/models/final.rb
class Final < Phase
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :table
  belongs_to :round
  has_many :scores, dependent: :destroy
  has_many :users, through: :scores
  accepts_nested_attributes_for :scores

end

app/models/nationality.rb
class Nationality < ActiveRecord::Base
  has_many :users
end

app/models/phase.rb
class Phase < ActiveRecord::Base
  belongs_to :tournament
  has_many :rounds
  has_and_belongs_to_many :users
  self.inheritance_column = :type

  def self.types
    %w(Qualification)
  end

  def name
    self.class.name.gsub(/_/, ' ').capitalize
  end

  def init
    raise "AbstractMethod"
  end

  def get_points_for_user_at_table(user, table)
    raise "AbstractMethod"
  end
end

app/models/qualification.rb
class Qualification < Phase

  def init
    self.tournament.users.each do |user|
      self.users << user    # assign each user from the tournament
    end
    self.save!
  end

  def get_points_for_user_at_table(user, table)
    user_score = Score.where(:user_id => user)
      .joins(:match).where('matches.table_id' => table, 'matches.round_id' => self.rounds)
      .first.value
    count_of_greater_scores = Score.joins(:match).where('matches.table_id' => table, 'matches.round_id' => self.rounds)
      .count(:conditions => ['scores.value > ?', user_score])

    self.users.count - count_of_greater_scores
  end

  def get_table_standing_for_user(user, table)
    self.users.count - get_points_for_user_at_table(user, table) + 1
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  include Comparable

  has_and_belongs_to_many :users

  def <=>(other)
    if self.name == 'SuperAdmin'
      return 0 if other.name == 'SuperAdmin'
      return 1
    elsif self.name == 'Admin'
      return -1 if other.name == 'SuperAdmin'
      return 0 if other.name == 'Admin'
      return 1
    else
      return 0 if other.name == 'Player'
      return -1
    end
  end
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :phase
  has_many :matches, dependent: :destroy
  has_many :users, through: :matches
  has_many :scores, through: :matches
  has_many :tables, through: :matches

  accepts_nested_attributes_for :matches
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :match
  belongs_to :user
  has_one :table, through: :match

  def empty?
    return ( self.value == 0 or self.value.nil? ) ? true : false
  end
end

app/models/table.rb
class Table < ActiveRecord::Base
  has_many :matches

  def get_points_for_player_in_current_phase(user_id, phase)
    user = User.find(user_id)
    phase.get_points_for_user_at_table(user, self)
  end

  def get_player_standing_at_table_in_current_phase(user_id, phase)
    user = User.find(user_id)
    phase.get_table_standing_for_user(user, self)
  end
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :phases, dependent: :destroy
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :phases

  def get_current_phase
    self.phases[self.current_phase]
  end

  def init
    self.phases[0].init
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_secure_token
  has_and_belongs_to_many :phases
  has_and_belongs_to_many :tournaments

  before_validation :capitalize_names
  before_validation :downcase_email

  belongs_to :nationality
  has_and_belongs_to_many :roles
  has_many :scores
  has_many :matches, through: :scores

  validates :first_name, :last_name, :email, :password_digest, presence: true
  validates :nationality_id, inclusion: { in: Nationality.ids }
  validates :email, format: { with: /\A[a-zA-Z0-9\.\+_]+@[a-zA-Z0-9_]+\.[a-zA-Z]+/}
  validates :email, uniqueness: { case_sensitive: false }
  validate :check_uniqueness_of_full_name, on: :create

  def self.get_player_count
    player = Role.find_by_name('Player')
    self.all.map { |user| user.roles.index(player) }.compact.length
  end

  def get_player_full_name
    self.first_name + " " + self.last_name
  end

  private

    def check_uniqueness_of_full_name
      if not User.find_by(first_name: first_name, last_name: last_name).nil?
        errors.add :first_name, 'Player with this name already exists'
        errors.add :last_name, 'Player with this name already exists'
      end
    end

    def capitalize_names
      first_name.capitalize!
      last_name.capitalize!
    end

    def downcase_email
      email.downcase!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_authorize(role)
    if session[:user_id]
      user = User.find(session[:user_id])
      required_role = Role.find_by_name(role)
      user.roles.each do |user_role|
        return true if user_role >= required_role
      end
    end
    return false
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def form_with_error_handling(name, &html)
     error = !@user.errors[name].empty?
     content_tag(:div, class: "form-group #{'form-group-no-margin-bottom' if error}") do
        content_tag(:div, class: nil) do
          res = [] << content_tag(:div, class: "input-group has-feedback #{'has-error' if error }") do
            res = []
            res << content_tag(:span, class: 'input-group-addon new-user-group-addon') do
              if name == :password_confirmation
                n = :confirm
              elsif name == :nationality_id
                n = :nationality
              else
                n = name
              end
              n.to_s.split(/_/).map {|t| t.capitalize }.join(" ")
            end
            res.append(yield html)
            if error
              res << content_tag(:span, class: 'form-control-feedback glyphicon glyphicon-remove') {}
            end
            res.join.html_safe
          end
          if error
            res << content_tag(:strong, @user.errors[name].first, class: 'help-block', style: 'color: red;')
          end
          res.join.html_safe
        end
      end
  end
end

app/views/shared/_alert_box.html.erb
<% if flash[:type] %>
    <div class="container">
      <div class="text-center alert alert-<%= "#{flash[:type].to_s}" %>">
        <%= flash[:message] %>
      </div>
    </div>
<% end %>

app/views/shared/_header.html.erb
  <nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-menu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Logo</a>
        </div>
      <div class="collapse navbar-collapse" id="nav-menu">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Roles<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "List all", roles_path %></li>
                <li><%= link_to "Create new", new_role_path %></li>
              </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'List all', users_path %></li>
              <li><%= link_to 'Add new', new_user_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Nationalities<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'List all', nationalities_path %></li>
              <li><%= link_to 'Add new', new_nationality_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/shared/_menu.html.erb
  <nav class="navbar navbar-default navbar-fixed-top">
    <!--<div class="container-fluid">-->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-menu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">PPO 2016</a>
        </div>
      <div class="collapse navbar-collapse" id="nav-menu">
<!--login -->
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><%= session[:user_id] ? User.find(session[:user_id]).get_player_full_name : 'Login' %></a>
            <ul class="dropdown-menu">
              <% if session[:user_id] %>

              <li><%= link_to 'Your profile', User.find(session[:user_id]) %></li>
              <li class="nav-divider"></li>
              <li><%= link_to 'Logoff', logout_path, method: :delete %></li>

              <% else %>

                <div style="min-width: 15em; margin: 5px;">
                  <%= render 'session/login' %>
                </div>

              <% end %>
            </ul>
          </li>
        </ul>

      <% if menu_authorize('SuperAdmin') %>

          <ul class="nav navbar-nav navbar-left">
            <li>
              <a href="#">Meta Administration</a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Tables', tables_path %></li>
                <li><%= link_to 'Roles', roles_path %></li>
                <li><%= link_to 'Nationalities', nationalities_path %></li>
              </ul>
            </li>
          </ul>

      <% end %>

      <% if menu_authorize('Admin') %>
        <% Tournament.all.each do |tournament| %>

          <ul class="nav navbar-nav navbar-left">
            <li>
              <a href="#"><%= tournament.name %></a>
              <ul class="dropdown-menu">
                <li><a href="#">Management</a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Enter score', new_tournament_match_path(tournament) %></li>
                  </ul>
                </li>
                <li><%= link_to 'Information', tournament %></li>
              </ul>
            </li>
          </ul>

        <% end %>
      <% end %>
      </div>
    <!--</div>-->
  </nav>

app/views/user_notifier/activated.text.erb
Hello there <%= @user.get_player_full_name %>.

Your account is now fully activater. Stay tuned as more features will be added soon.

app/views/user_notifier/created.text.erb
Hello there <%= @user.get_player_full_name %>!

Thanks for registering in our super awesome tournament app. In order to activate your account please follow the below link:

<%= "http://home.dylux.net/users/#{@user.id}/activate?token=#{@user.token}" %>

app/views/user_notifier/pass_reset.text.erb
Hello there <%= @user.get_player_full_name %>!

You can update your password using the following url:

<%= "http://home.dylux.net/users/#{@user.id}/edit?token=#{@user.token}" %>